{
  "openapi": "3.0.0",
  "info": {
    "title": "triveous-Ecommerce-API",
    "description": "Welcome to our E-Commerce project! This project is built using Node.js and Express and serves as an e-commerce platform. This Documentation provides an overview of the API routes available in the application",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://successful-worm-glasses.cyclic.cloud/",
      "description": "cyclic deployed url"
    },
    {
      "url": "http://localhost:8080/",
      "description": "Local server"
    }
  ],
  "components": {
    "schemas": {
      "users": {
        "type": "object",
        "required": [
          "name",
          "email",
          "password",
          "role"
        ],
        "properties": {
          "_id": {
            "type": "string",
            "description": "he auto-generated id of the user (MongoDB ObjectID)"
          },
          "name": {
            "type": "string",
            "description": "The user fullname"
          },
          "email": {
            "type": "string",
            "description": "The user email"
          },
          "password": {
            "type": "string",
            "description": "The user password"
          },
          "role": {
            "type": "string",
            "default": "User",
            "enum": [
              "User",
              "Admin"
            ],
            "description": "The user role"
          },
          "addresses": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The user addresses"
          }
        }
      },
      "products": {
        "type": "object",
        "required": [
          "title",
          "description",
          "price",
          "brand",
          "category"
        ],
        "properties": {
          "_id": {
            "type": "string",
            "description": "The auto-generated id of the user (MongoDB ObjectID)"
          },
          "title": {
            "type": "string",
            "description": "The product title"
          },
          "description": {
            "type": "string",
            "description": "The product description"
          },
          "price": {
            "type": "number",
            "minimum": 1,
            "description": "The product price"
          },
          "rating": {
            "type": "number",
            "minimum": 1,
            "maximum": 5,
            "description": "The product rating"
          },
          "stock": {
            "type": "number",
            "minimum": 0,
            "default": 0,
            "description": "The product in stock available"
          },
          "brand": {
            "type": "string",
            "description": "The brand of the product"
          },
          "category": {
            "type": "string",
            "description": "The product category"
          },
          "deleted": {
            "type": "boolean",
            "description": "deleted ststus of the product"
          }
        }
      },
      "categories": {
        "type": "object",
        "required": [
          "label"
        ],
        "properties": {
          "_id": {
            "type": "string",
            "description": "The auto-generated id of the user (MongoDB ObjectID)"
          },
          "label": {
            "type": "string",
            "description": "The category label"
          },
          "description": {
            "type": "string",
            "description": "The category description"
          }
        }
      },
      "carts": {
        "type": "object",
        "required": [
          "quantity",
          "product",
          "user"
        ],
        "properties": {
          "_id": {
            "type": "string",
            "description": "The auto-generated id of the user (MongoDB ObjectID)"
          },
          "quantity": {
            "type": "number",
            "description": "total quantity pf cart"
          },
          "product": {
            "type": "string",
            "$ref": "#/components/schemas/products/properties/_id",
            "description": "product id - MongoDB ObjectId (_id)"
          },
          "user": {
            "type": "string",
            "$ref": "#/components/schemas/users/properties/_id",
            "description": "userId of the customer - MongoDB ObjectId (_id)"
          }
        }
      },
      "orders": {
        "type": "object",
        "required": [
          "items",
          "totalAmount",
          "totalItems",
          "user",
          "paymentMethod",
          "selectedAddress"
        ],
        "properties": {
          "_id": {
            "type": "string",
            "description": "The auto-generated id of the user (MongoDB ObjectID)"
          },
          "items": {
            "type": "array",
            "items": {
              "type": "string",
              "$ref": "#/components/schemas/products/properties/_id",
              "description": "The ordered items"
            }
          },
          "totalAmount": {
            "type": "number",
            "description": "total order amount value"
          },
          "totalItems": {
            "type": "number",
            "description": "total number of items"
          },
          "user": {
            "type": "string",
            "$ref": "#/components/schemas/users/properties/_id",
            "description": "userId of the customer - MongoDB ObjectId (_id)"
          },
          "paymentMethod": {
            "type": "string",
            "enum": [
              "card",
              "cash"
            ],
            "description": "payment method used for the order"
          },
          "paymentStatus": {
            "type": "string",
            "default": "pending",
            "description": "payment status of the order"
          },
          "status": {
            "type": "string",
            "default": "pending",
            "description": "current status of the order"
          },
          "selectedAddress": {
            "type": "string",
            "description": "address to deliver the order"
          },
          "deleted": {
            "type": "boolean",
            "default": true,
            "description": "deleted status of the order"
          }
        }
      }
    },
    "securitySchemes": {
      "bearer_token_Auth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "add your JWT token here, it will be prefixed with 'Bearer '"
      },
      "bearer_refresh_token_Auth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "add your JWT refresh token here, it will be prefixed with 'Bearer '"
      }
    }
  },
  "tags": [
    {
      "name": "User",
      "description": "All the API routes related to User"
    },
    {
      "name": "Product",
      "description": "All the API routes related to Product"
    },
    {
      "name": "Category",
      "description": "All the API routes related to Category"
    },
    {
      "name": "Cart",
      "description": "All the API routes related to Cart"
    },
    {
      "name": "Order",
      "description": "All the API routes related to Order"
    }
  ],
  "paths": {
    "/user/signup": {
      "post": {
        "summary": "User SignUp",
        "tags": [
          "User"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Joao Cancelo",
                  "email": "joaocancelo@gmail.com",
                  "password": "joaocancelo",
                  "role": "User"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "A new user signs up",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "User created successfully"
                  }
                }
              }
            }
          },
          "406": {
            "description": "If passed role is Admin",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Only an Admin can create new Admin"
                  }
                }
              }
            }
          },
          "400": {
            "description": "User already exists",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "User already exists"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "something went wrong"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "summary": "User Login",
        "tags": [
          "User"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "joaocancelo@gmail.com",
                  "password": "joaocancelo"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login successfull",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Login successfull",
                    "token": "<JWT Token>",
                    "refreshtoken": "<JWT refresh Token>"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Invalid username or password",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Invalid username or password"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "something went wrong"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/addresses": {
      "post": {
        "summary": "Add Address",
        "tags": [
          "User"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "address": "18 RNC Road Subhasgram"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer_token_Auth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Address Added",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Address Added successfully"
                  }
                }
              }
            }
          },
          "401": {
            "description": "address not provided",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Please Provide a new address to be added"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "something went wrong",
                    "error": "<error message>"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/logout": {
      "get": {
        "summary": "User Logout, token will be blacklisted",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearer_token_Auth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Logout successfull",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Logout successfull"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Token not provided or token blacklisted",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Unauthorized"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/getnewtoken": {
      "get": {
        "summary": "Get new JWT token from the refresh token",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearer_refresh_token_Auth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Get new JWT token with the refresh token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "token": "<JWT Token>"
                  }
                }
              }
            }
          },
          "501": {
            "description": "Invalid username or password",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Invalid refresh token, please login again"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "something went wrong",
                    "error": "<Error message>"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/profile": {
      "get": {
        "summary": "Get profile details",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearer_token_Auth": []
          }
        ],
        "responses": {
          "200": {
            "description": "profile details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "profile": {
                      "_id": "<User id>",
                      "name": "<User Name>",
                      "email": "<User email>",
                      "role": "<User role>"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "JWT expired",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Unauthorized",
                    "error": "Error message"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/adminsignup": {
      "post": {
        "summary": "Only admin can signup another admin, provide JWT token of another admin.",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearer_token_Auth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Robert Lewandowski",
                  "email": "robertlewandowski@gmail.com",
                  "password": "robertlewandowski",
                  "role": "Admin"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "A new Admin signs up",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Admin created successfully"
                  }
                }
              }
            }
          },
          "406": {
            "description": "If passed role is other than 'Admin'",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Specify role as Admin"
                  }
                }
              }
            }
          },
          "401": {
            "description": "If token error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Unauthorized",
                    "error": "<Error message>"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Admin already exists",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Admin already exists"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "something went wrong"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/deleteuser": {
      "delete": {
        "summary": "Only an admin can Delete User/Admin, provide JWT token of another admin.",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearer_token_Auth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "robertlewandowski@gmail.com"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User Deleted",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "User Deleted Successfully"
                  }
                }
              }
            }
          },
          "401": {
            "description": "If token error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Unauthorized",
                    "error": "<Error message>"
                  }
                }
              }
            }
          },
          "400": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "User not found"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "something went wrong"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products": {
      "post": {
        "summary": "Only Admin can create new Product, provide admin JWT token",
        "tags": [
          "Product"
        ],
        "security": [
          {
            "bearer_token_Auth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "title": "iPhone 15 Pro Max",
                  "description": "Introducing the all new iPhone 15 pro max, Again, this time we have only changed the number, nothing new here",
                  "price": 160000,
                  "rating": 5,
                  "stock": 10000,
                  "brand": "Apple",
                  "category": "Mobiles",
                  "deleted": false
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "A New Product Added Successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "New Product Added Successfully",
                    "product": {
                      "_id": "<MongoDB ObjectID>",
                      "title": "iPhone 15 Pro Max",
                      "description": "Introducing the all new iPhone 15 pro max, Again, this time we have only changed the number, nothing new here",
                      "price": 160000,
                      "rating": 5,
                      "stock": 10000,
                      "brand": "Apple",
                      "category": "Mobiles",
                      "deleted": false
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Error creating product or missing required fields",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Missing required fields"
                  }
                }
              }
            }
          },
          "401": {
            "description": "If token error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Unauthorized",
                    "error": "<Error message>"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "<Error message>"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/{id}": {
      "patch": {
        "summary": "Only Admin can update Product, provide admin JWT token",
        "tags": [
          "Product"
        ],
        "security": [
          {
            "bearer_token_Auth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The product id (MongoDB ObjectID)",
            "required": true,
            "schema":{
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "title": "Luxury iPhone 14 Pro ",
                  "description": "Introducing the all new iPhone 15 pro max, Again, this time we have only changed the number, nothing new here",
                  "price": 50000,
                  "rating": 2,
                  "stock": 500,
                  "brand": "Apple",
                  "category": "Mobiles",
                  "deleted": false
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Product Updated Successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "New Product Added Successfully",
                    "product": {
                      "_id":"<MongoDB ObjectID>",
                      "title": "Luxury iPhone 14 Pro ",
                      "description": "Introducing the all new iPhone 15 pro max, Again, this time we have only changed the number, nothing new here",
                      "price": 50000,
                      "rating": 2,
                      "stock": 500,
                      "brand": "Apple",
                      "category": "Mobiles",
                      "deleted": false
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Error updating product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "<Error message>"
                  }
                }
              }
            }
          },
          "401": {
            "description": "If token error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Unauthorized",
                    "error": "<Error message>"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "get Product by id",
        "tags": [
          "Product"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The product id (MongoDB ObjectID)",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Product details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "product": {
                      "_id": "<MongoDB ObjectID>",
                      "title": "Luxury iPhone 14 Pro ",
                      "description": "Introducing the all new iPhone 15 pro max, Again, this time we have only changed the number, nothing new here",
                      "price": 50000,
                      "rating": 2,
                      "stock": 500,
                      "brand": "Apple",
                      "category": "Mobiles",
                      "deleted": false
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Error getting product details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "<Error message>"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}